# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5835f2fec30c8b7babea9b32481c93796333b37fa7d1aaa30e3255b95e87f1d61b0aa354730360a7738b7f4656fd4543f691d52cc70e0133a23d815f9622a1bf

test:
  secret_key_base: cdc2e9a126135ba18ed01d95e38c23c8262cebbdf04709248abfb513b42c7c5630911d2f16961df4eccf2eddb90ec4b22d85d147d5767cebbf96b66874bb08b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
